### ISSUE TITLE
Superbox not removed, windows controls alignment wrong without title bar

### ISSUE THREAD

**Issue by menguele** [drannex42/FirefoxSidebar#20]
OS:Windows 10

When not using the title bar this is what it appears to be like:
https://imgur.com/a/Rp0nxXt
Additionaly the url bar disappear as does the url/history box when selected.

**Comment by drannex42** [comment]
I recently installed this on Windows (yesterday, in fact) and noticed the same thing. I normally use linux distros. 

The solution for the close buttons is to set the csd preference to 0px. I will be updating how this all fits together with better defaults per OS very soon. There are a number of quality changes that need to be updated. 

Superbox _effects_ appears to be removed, but the url bar disappearing is strange, could you send a screenshot of what happens when you click on that? I can't reproduce.

**Comment by menguele** [comment]
I couldn't replicate the disappearing of the url bar either, probably was firefox not liking something.

Could you be more specific for what changes in the prefs have to be made?

**Comment by eissar** [comment]
I added this code to the CSS and it worked:
:root[tabsintitlebar][sizemode="normal"] #titlebar {
  appearance: none !important;
}
this mostly works but hides the close button
https://imgur.com/6r2OQ7G

**Comment by eissar** [comment]
So this seems to have full functionality. might be hacky. but it looks pretty good!
add this to custom.css:
  ```
 :root[tabsintitlebar] #titlebar {
    appearance: none !important;
  }
  
#sidebar-box {
    margin-top: -42px !important;
} 
/* fix later */
```
  
  and change the following values in prefs.css:
  ```
      --csd-width: 142.5px;
      --csd-margin-right: 150px; 
```
you can set 'csd-margin-right' lower, i just made it this way so there is more drag space. i think 137.5px is the lowest.


note : doesnt work with the themes

**Comment by eissar** [comment]
warning, don't set density to touch it makes things very weird...

**Comment by drannex42** [comment]
This is roughly the right solution, and what I've had to do on my own Windows install. Really wish I could find the time to upgrade the entire repo to have per-os defaults, they will make their way eventually, 

I'll mark this closed for the time being as @eissar has a handle and solution on this.
