### ISSUE TITLE
Sidebery 5.0.0 was released today [Working Thread: New Style Inside for Testing]

### ISSUE THREAD

**Issue by xfzv** [drannex42/FirefoxSidebar#41]
[Sidebery 5.0.0 was released today](https://github.com/mbnuqw/sidebery/releases/tag/v5.0.0). Several things are broken when Sidebery is collapsed:

- The top icons aren't rendered well:

![image](https://github.com/drannex42/FirefoxSidebar/assets/78810647/25e5f83c-e22f-4657-b2c4-2f4a112020ac)

![image](https://github.com/drannex42/FirefoxSidebar/assets/78810647/29d17225-67fa-4a53-b93e-634dd3d6a592)

- And so are the bottom ones:

![image](https://github.com/drannex42/FirefoxSidebar/assets/78810647/bb84cc00-868a-40bc-8e39-ca3a5b72d882)

![image](https://github.com/drannex42/FirefoxSidebar/assets/78810647/4d076faf-b81e-4a12-9dfa-c65ec5b5c933)

 - Favicons aren't centered vertically (compare with the new tab ("+") button):

![image](https://github.com/drannex42/FirefoxSidebar/assets/78810647/bce51d5f-268f-4ab1-b4dc-98ea89261af9)

- Some tabs icons are invisible if disabling "Show new tab buttons" in Sidebery settings

![image](https://github.com/drannex42/FirefoxSidebar/assets/78810647/3461e7b8-810e-43c8-904a-1e782ad0a6d9)

![image](https://github.com/drannex42/FirefoxSidebar/assets/78810647/8612db04-6cbb-43b5-adf9-9c863b247b71)

- `Ctrl+E` to open/close sidebar panel no longer works (tested on a blank profile without `FirefoxSidebar`, works)

**Comment by drannex42** [comment]
Yes, this was a failure on my part. I modified the existing theme instead of creating one from scratch, this causes issues when they release an update like this. 

I will look into SideBerry v5 and try to recreate the theme from *scratch* this time. I am currently using the [Floorp browser](https://github.com/floorp-Projects/floorp/) (Firefox, modified, adds a lot more features similar to Vivaldi) and I am seeing the same problem with the new version. 

I am unsure about Ctrl+E as nothing I added/modified would hamper that (nor have I ever used it, cool tip!)

**Comment by drannex42** [comment]
The new Sideberry is damn impressive. 

I don't have to recreate everything, this is so much better. 

Just add this to your custom css in Sideberry > Styles > Edit Style > Custom CSS

`

**Comment by drannex42** [comment]
Nothing else, just that, and it'll even open a thousand more options for you to style to your liking.

**Comment by drannex42** [comment]
Interesting, remove all existing css from the block and add the newly updated version I added above (v12023.09.19-1) 

Will look something like this in settings:

![image](https://github.com/drannex42/FirefoxSidebar/assets/4322153/0dc4a62c-c4e9-4eaa-ba43-89dd59c8eb05)

**Comment by drannex42** [comment]
Have you tried modifying the margin variables? If you set it likely 8px or 8.5px you will likely have it centered and not see the letters.

**Comment by drannex42** [comment]
I've updated the styling above. Now no matter what the title will not be shown on the minimized sidebar, and I've changed from using a custom inner padding class to the one Sidebery has already defined. You should be able to use that to center your icons better. 

Changes (v12023.09.20): 
- Title will no longer be shown in minimized state.
- Changed custom inner padding to built-in Sidebery styling option. 
- Container indicators are now on the left, instead of the right. 
- Audio indicator is now placed in the lower right in minimized and expanded state instead of inline with the tab title. 
- Added some additional notes.

**Comment by drannex42** [comment]
**Changes (v12023.09.25)**
- I've added a `--nav-height-padding` variable, that way when you change the general margin, but you can keep the navbar height slimmer than the tabs.

**Comment by drannex42** [comment]
Closing this as I just released the latest version with the official release of Sidebery 5.

https://github.com/drannex42/FirefoxSidebar/releases/tag/v2024.05.15
