### ISSUE TITLE
v2024.05.15 - how to use full width for URL bar?

### ISSUE THREAD

**Issue by xfzv** [drannex42/FirefoxSidebar#49]
I've updated to v2024.05.15 today.

Before, the URL bar used to use the full width:
![image](https://github.com/drannex42/FirefoxSidebar/assets/78810647/98ff1169-9d8d-43bb-a0b2-16779422b70a)

Now, the sidebar takes the full height:
![image](https://github.com/drannex42/FirefoxSidebar/assets/78810647/f22d6baf-39a9-4e6a-80e8-df152aaefa5a)

How could I get the old behavior back?

I tried to enable [superbox_removal.css](https://github.com/drannex42/FirefoxSidebar/blob/main/extensions/superbox_removal.css) again in `userChrome.css`:

```css
@import url("./extensions/superbox_removal.css");
```

but it doesn't make any difference. I noticed that the extension was not just commented but actually [removed from `userChrome.css`](https://github.com/drannex42/FirefoxSidebar/commit/ae6473195b38f07f66b5dbc158807c51e5feed12#diff-2f47ee8e5f8520c45fa369ed4e435af21b8273494d3d81eaa9b72ed77ca2f635L34-L36) so I guess it's no longer compatible with v2024.05.15 (not sure why [superbox_removal.css](https://github.com/drannex42/FirefoxSidebar/blob/main/extensions/superbox_removal.css) file is still in the repo though).

Thanks!

**Comment by drannex42** [comment]
Interesting — you must have had a bug this entire time! The address bar was never supposed to be full width. The sidebar was supposed to be entirely on the left side. Your address bar was actually blocking the ability to switch different sidebars this entire time.

The superbox_removal extension was never supposed to do that, and it's removal shouldn't have technically fixed this issue for you either, it's more than likely due to how we rewrote the core sidebar file and how it positions itself to be a fair bit more stable and less buggy. 

You do though, I believe, need to enable either your bookmark bar, or enable the bookmark bar fix to have that set itself properly from what I can sort of tell from those screenshots.

**Comment by drannex42** [comment]
Thanks for filing the issue! I'll take a look, there might be some additional testing needed to set the values properly for most people on first load. I'll take a look around next week and try to get a fix sent out.

There also has to be a way to autodetect the bookmark bar, I'll see if there is anything in `about:config` to detect and apply CSS. Unsure if possible, but I hope so!

I'll keep the issue open until I find out more.
